name: Update Amul API Headers

on:
  schedule:
    - cron: '0 */2 * * *'  # Every 2 hours
  workflow_dispatch:       # Allow manual runs

jobs:
  update-headers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          echo "CHROME_BINARY=/usr/bin/chromium-browser" >> $GITHUB_ENV

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_FILENAME: ${{ secrets.GIST_FILENAME }}
        run: |
          python fetch_cookie_and_update.py
