name: Amul API Cookie Fetch & Gist Update

on:
  schedule:
    - cron: '0 */4 * * *'  # Every 2 hours
  workflow_dispatch:

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest
    env:
      TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
      GIST_ID: ${{ secrets.GIST_ID }}
      GIST_FILENAME: api_url_and_headers.json
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          echo "CHROME_BINARY=/usr/bin/chromium-browser" >> $GITHUB_ENV

      - name: Run fetch_cookie_and_update.py
        run: python fetch_cookie_and_update.py
